# Generated by Django 4.1.7 on 2023-05-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='players_connected',
            field=models.IntegerField(default=0),
        ),
    ]
